timezone: "Europe/Stockholm"
cloudstack_repo: "deb http://download.cloudstack.org/ubuntu jammy 4.19\n"
templates_path: "{{playbook_dir}}/templates"
api_local_git_url: "https://github.com/kthcloud/host-api"
apps_install_path: "/opt"
