---
- name: Update LCD message
  ansible.builtin.import_role:
    name: lcd-update
  vars:
    lcd_message: "Installing required PIP packages"

- name: Install all pip dependencies
  pip:
    name: ["jc"]
    state: latest
